model_name: trace
results_dirname: 01-trace
gpu:
- 1
seed: 0
results_path: .
dataset_root: datasets/008-Sand-2D
n_val: 16
radius: 0.0036
skin_factor: null
memory: none
hidden_dim: 128
memory_dim: 16
normalize_inputs: true
boundary_features: true
sample_weighting: motion
loss: mse
epochs: 2000
decay_epochs: 300
early_stop_patience: 120
warmup_steps: 100
val_rollout: 300
eval_interval: 20
lr: 0.0003
lr_min: 3.0e-06
n_train: 512
num_layers: 8
rollout_steps: 15
noise: 0.0004
target_correction: true
vel_from_displacement: true
exp_name: ablation/mem-none/01-pretrain
